/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.7.7-362
 *
 */
import { CallParams } from '@fluencelabs/interfaces';
import { registerService } from '../../compilerSupport/registerService.js';
import { FluencePeer } from '../../jsPeer/FluencePeer.js';

// Services

export interface NodeUtilsDef {
    read_file: (
        path: string,
        callParams: CallParams<'path'>,
    ) =>
        | { content: string | null; error: string | null; success: boolean }
        | Promise<{ content: string | null; error: string | null; success: boolean }>;
}

export function registerNodeUtils(peer: FluencePeer, serviceId: string, service: any) {
    registerService({
        peer: peer as any,
        service: service,
        serviceId: serviceId,
        def: {
            defaultServiceId: 'node_utils',
            functions: {
                tag: 'labeledProduct',
                fields: {
                    read_file: {
                        tag: 'arrow',
                        domain: {
                            tag: 'labeledProduct',
                            fields: {
                                path: {
                                    tag: 'scalar',
                                    name: 'string',
                                },
                            },
                        },
                        codomain: {
                            tag: 'unlabeledProduct',
                            items: [
                                {
                                    tag: 'struct',
                                    name: 'ReadFileResult',
                                    fields: {
                                        content: {
                                            tag: 'option',
                                            type: {
                                                tag: 'scalar',
                                                name: 'string',
                                            },
                                        },
                                        error: {
                                            tag: 'option',
                                            type: {
                                                tag: 'scalar',
                                                name: 'string',
                                            },
                                        },
                                        success: {
                                            tag: 'scalar',
                                            name: 'bool',
                                        },
                                    },
                                },
                            ],
                        },
                    },
                },
            },
        },
    });
}

// Functions
