# yaml-language-server: $schema=schemas/docker-compose.json

# The Compose file is a YAML file defining a multi-containers based application.

# Documentation: https://github.com/fluencelabs/cli/tree/main/docs/configs/docker-compose.md

version: "3"

volumes:
  ipfs: null
  nox-0: null
  nox-1: null
  nox-2: null

secrets:
  nox-0:
    file: secrets/nox-0.txt
  nox-1:
    file: secrets/nox-1.txt
  nox-2:
    file: secrets/nox-2.txt

services:
  ipfs:
    image: ipfs/kubo
    ports:
      - 5001:5001
      - 4001:4001
    environment:
      IPFS_PROFILE: server
    volumes:
      - ipfs:/data/ipfs
    healthcheck:
      test: ipfs id || exit 1
      interval: 8s
      timeout: 10s
      retries: 20
  nox-0:
    image: docker.fluence.dev/nox:feat-vm-425-aquavm-mem-limits-from-config-2_5056_1
    ports:
      - 7771:7771
      - 9991:9991
    environment:
      WASM_LOG: debug
      FLUENCE_MAX_SPELL_PARTICLE_TTL: 9s
      FLUENCE_ROOT_KEY_PAIR__PATH: /run/secrets/nox-0
      RUST_LOG: chain_connector=debug,run-console=trace,aquamarine::log=debug,network=trace,worker_inactive=trace
    command:
      - --config=/run/configs/nox-0_Config.toml
      - --dev-mode
      - --external-maddrs
      - /dns4/nox-0/tcp/7771
      - /dns4/nox-0/tcp/9991/ws
      - --allow-private-ips
      - --local
    depends_on:
      ipfs:
        condition: service_healthy
    volumes:
      - ./configs/nox-0_Config.toml:/run/configs/nox-0_Config.toml
      - nox-0:/.fluence
    secrets:
      - nox-0
    healthcheck:
      test: curl -f http://localhost:18080/health
      interval: 5s
      timeout: 2s
      retries: 10
  nox-1:
    image: docker.fluence.dev/nox:feat-vm-425-aquavm-mem-limits-from-config-2_5056_1
    ports:
      - 7772:7772
      - 9992:9992
    environment:
      WASM_LOG: debug
      FLUENCE_MAX_SPELL_PARTICLE_TTL: 9s
      FLUENCE_ROOT_KEY_PAIR__PATH: /run/secrets/nox-1
      RUST_LOG: chain_connector=debug,run-console=trace,aquamarine::log=debug,network=trace,worker_inactive=trace
    command:
      - --config=/run/configs/nox-1_Config.toml
      - --external-maddrs
      - /dns4/nox-1/tcp/7772
      - /dns4/nox-1/tcp/9992/ws
      - --allow-private-ips
      - --bootstraps=/dns/nox-0/tcp/7771
    depends_on:
      ipfs:
        condition: service_healthy
    volumes:
      - ./configs/nox-1_Config.toml:/run/configs/nox-1_Config.toml
      - nox-1:/.fluence
    secrets:
      - nox-1
    healthcheck:
      test: curl -f http://localhost:18080/health
      interval: 5s
      timeout: 2s
      retries: 10
  nox-2:
    image: docker.fluence.dev/nox:feat-vm-425-aquavm-mem-limits-from-config-2_5056_1
    ports:
      - 7773:7773
      - 9993:9993
    environment:
      WASM_LOG: debug
      FLUENCE_MAX_SPELL_PARTICLE_TTL: 9s
      FLUENCE_ROOT_KEY_PAIR__PATH: /run/secrets/nox-2
      RUST_LOG: chain_connector=debug,run-console=trace,aquamarine::log=debug,network=trace,worker_inactive=trace
    command:
      - --config=/run/configs/nox-2_Config.toml
      - --dev-mode
      - --external-maddrs
      - /dns4/nox-2/tcp/7773
      - /dns4/nox-2/tcp/9993/ws
      - --allow-private-ips
      - --bootstraps=/dns/nox-0/tcp/7771
    depends_on:
      ipfs:
        condition: service_healthy
    volumes:
      - ./configs/nox-2_Config.toml:/run/configs/nox-2_Config.toml
      - nox-2:/.fluence
    secrets:
      - nox-2
    healthcheck:
      test: curl -f http://localhost:18080/health
      interval: 5s
      timeout: 2s
      retries: 10
