aquavm_pool_size = 2
tcp_port = 7_773
websocket_port = 9_993
http_port = 18_082

[system_services]
enable = [ "aqua-ipfs", "decider" ]

  [system_services.aqua_ipfs]
  external_api_multiaddr = "/ip4/127.0.0.1/tcp/5001"
  local_api_multiaddr = "/dns4/ipfs/tcp/5001"

  [system_services.decider]
  decider_period_sec = 10
  worker_ipfs_multiaddr = "/dns4/ipfs/tcp/5001"
  network_api_endpoint = "http://chain-rpc:8545"
  network_id = 31_337
  start_block = "earliest"
  matcher_address = "0x3Aa5ebB10DC797CAC828524e59A333d0A371443c"
  wallet_key = "0x16e3984df2918538c5dbba032f00a5ecd5900b9c43a36b38ed89b6be1820a9ba"

[chain_config]
http_endpoint = "http://chain-rpc:8545"
core_contract_address = "0x0B306BF915C4d645ff596e518fAf3F9669b97016"
cc_contract_address = "0xc6e7DF5E7b4f2A278906862b61205850344D4e7d"
market_contract_address = "0x3Aa5ebB10DC797CAC828524e59A333d0A371443c"
network_id = 31_337
wallet_key = "0x16e3984df2918538c5dbba032f00a5ecd5900b9c43a36b38ed89b6be1820a9ba"

[effectors.curl]
wasm_cid = "bafkreigkoxnkeyunbelr5qhqbt5nspaew7uysd2trdds346rrogfz3zvuq"

  [effectors.curl.allowed_binaries]
  curl = "/usr/bin/curl"
