/* eslint-disable */
// @ts-nocheck
/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.12.0
 *
 */
import type { IFluenceClient as IFluenceClient$$, CallParams as CallParams$$ } from '@fluencelabs/js-client';
import {
    v5_callFunction as callFunction$$,
    v5_registerService as registerService$$,
} from '@fluencelabs/js-client';
    


// Services

// Functions
export const test_script = `
                    (seq
                     (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                     (xor
                      (xor
                       (call -relay- ("op" "noop") [])
                       (fail %last_error%)
                      )
                      (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 0])
                     )
                    )
    `
 

export function test(
    config?: {ttl?: number}
): Promise<void>;

export function test(
    peer: IFluenceClient$$,
    config?: {ttl?: number}
): Promise<void>;

export function test(...args: any) {


    return callFunction$$(
        args,
        {
    "functionName" : "test",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                
            }
        },
        "codomain" : {
            "tag" : "nil"
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        test_script
    )
}

/* eslint-enable */