# yaml-language-server: $schema=schemas/provider-secrets.json

# Defines secrets config used for provider set up

# Documentation: https://github.com/fluencelabs/cli/tree/main/docs/configs/provider-secrets.md

version: 0

noxes:
  nox-0:
    networkKey: t/7R5m9TprvbWFwr2ZKe8hm6UW84ulDq4pVbDvHUCdw=
    signingWallet: "0x3785b85a34b65082664bdb2ccb47fba6aab6984b7c16b36ad54145eecc368e4c"
  nox-1:
    networkKey: +5VkzeaILY+Emk9zsLKJ82dzzF3fMmlFkNhkJVwDMdo=
    signingWallet: "0xd9a5eee84979d0cf118f82f7c97ca6980e6a21db0c7271a3d59248841ed04d83"
  nox-2:
    networkKey: YNq7A6KlPhdyJwq7y3meTIPUVQ34HFwW21MlsDjpxsM=
    signingWallet: "0x16e3984df2918538c5dbba032f00a5ecd5900b9c43a36b38ed89b6be1820a9ba"
