name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/tests.yml"
      - "!.github/workflows/snapshot.yml"
    types:
      - "labeled"
      - "synchronize"
      - "opened"
      - "reopened"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/tests.yml"
      - "!.github/workflows/snapshot.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  js-client:
    if: >
      github.event_name == 'push' ||
      contains(github.event.pull_request.labels.*.name, 'e2e')
    uses: ./.github/workflows/snapshot.yml
    with:
      ref: ${{ github.ref }}

  aqua:
    needs:
      - js-client

    uses: fluencelabs/aqua/.github/workflows/tests.yml@main
    with:
      js-client-snapshots: "${{ needs.js-client.outputs.js-client-snapshots }}"

  fluence-cli:
    needs:
      - js-client

    uses: fluencelabs/fluence-cli/.github/workflows/tests.yml@main
    with:
      js-client-snapshots: "${{ needs.js-client.outputs.js-client-snapshots }}"
