name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/tests.yml"
      - "!.github/workflows/snapshot.yml"
  push:
    branches:
      - "master"
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/tests.yml"
      - "!.github/workflows/snapshot.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  tests:
    name: "js-client"
    uses: ./.github/workflows/tests.yml
    with:
      ref: ${{ github.ref }}

  js-client:
    uses: ./.github/workflows/snapshot.yml
    with:
      ref: ${{ github.ref }}

  aqua-playground:
    needs:
      - js-client

    uses: fluencelabs/aqua-playground/.github/workflows/tests.yml@master
    with:
      js-client-snapshots: "${{ needs.js-client.outputs.js-client-snapshots }}"

  status:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - aqua-playground

    steps:
      - uses: lwhiteley/dependent-jobs-result-check@v1
        id: status
        with:
          statuses: failure,cancelled,skipped
          dependencies: ${{ toJSON(needs) }}

      - name: Log output
        run: |
          echo "statuses:" "${{ steps.status.outputs.statuses }}"
          echo "jobs:" "${{ steps.status.outputs.jobs }}"
          echo "found any?:" "${{ steps.status.outputs.found }}"

      - name: Fail run
        if: fromJSON(steps.status.outputs.found)
        run: exit 1
