name: "Make github release"

on:
  workflow_dispatch:

jobs:
  release-github:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "Get the version of fluence-js package"
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.2.3
        with:
            path: packages/fluence-js

      - name: Set env
        run: echo "RELEASE_VERSION=v${{ steps.package-version.outputs.current-version }}" >> $GITHUB_ENV

      - name: "Create tag for release"
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.RELEASE_VERSION }}
          message: ""
          github_token: ${{ secrets.GITHUB_TOKEN }}

      ### Create a release
      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: ".github/workflows/changelog_config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          name: Fluence JS ${{ env.RELEASE_VERSION }}
          tag_name: ${{ env.RELEASE_VERSION }}
          body: ${{steps.changelog.outputs.changelog}}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}