name: "Release packages"

on:
  workflow_dispatch:

jobs:
  release-packages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
            version: 7

      - name: "Setup node"
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: 'https://registry.npmjs.org'

      - name: "Build packages"
        run: |
            pnpm i
            pnpm -r build

      - name: "Publish to npmjs.com"
        run: |
            result=$(pnpm --no-git-checks -r publish -filter '@fluencelabs/*' --access public)
            if [[ $result == "There are no new packages that should be published" ]]
            then
                echo ERROR: no packages have been published. Did you forget to bump version?
                exit 1
            fi
        env:
            CI: true
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

