name: "Release"

on:
  workflow_dispatch:

jobs:
  npm-publish:
    name: "Publish"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    strategy:
        matrix:
            node-version: [17.x]

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
            version: 7

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'pnpm'

      - name: Build Fluence JS
        run: |
            pnpm i
            pnpm -r build
        env:
           CI: true

      - name: Release Fluence JS
        run: |
            pnpm -r publish --dry-run
        env:
            CI: true

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
            path: packages/fluence-js

      - run: echo ${{ steps.package-version.outputs.current-version}}

    #  - uses: actions-ecosystem/action-push-tag@v1
    #    with:
    #      tag: ${{ steps.package-version.outputs.current-version}}

    #   - name: Build Changelog
    #     id: changelog
    #     uses: mikepenz/release-changelog-builder-action@v1
    #     with:
    #         configuration: ".github/workflows/changelog_config.json"
    #     env:
    #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    #   - name: Release
    #     id: release
    #     uses: softprops/action-gh-release@v1
    #     with:
    #         name: Fluence JS ${{ env.RELEASE_VERSION }}
    #         tag_name: ${{ env.RELEASE_VERSION }}
    #         body: ${{steps.changelog.outputs.changelog}}
    #         draft: false
    #         prerelease: false
    #     env:
    #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
