name: "Release packages"

on:
  workflow_dispatch:
  push:
    branches:
      - 'DXJ-85'

jobs:
  release-packages:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
        
      - uses: pnpm/action-setup@v2.2.2
        with:
            version: 7

      - name: "Setup node with self-hosted npm registry"
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://npm.fluence.dev"

      - name: "Build packages"
        run: |
            pnpm i
            pnpm -r build

      - name: "Import secrets"
        uses: hashicorp/vault-action@v2.4.2
        with:
          url: https://vault.fluence.dev
          path: jwt/github
          role: ci
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          exportToken: false
          secrets: |
            kv/npm-registry/basicauth/ci token | NODE_AUTH_TOKEN

      - name: "Publish to npmjs.com"
        run: |
            pnpm -r publish --dry-run --no-git-checks --registry https://npm.fluence.dev
        env:
            CI: true

      - name: "Get the version of fluence-js package"
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
            path: packages/fluence-js

      - name: "Create tag for release"
        run: |
          tag=${{ steps.bump-semver.outputs.new_version }}
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "${tag}" -m ""
          git push origin "${tag}"
