name: Run tests

on:
  pull_request:
    paths-ignore:
      - "**.md"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  fluence-js:
    uses: ./.github/workflows/tests.yml

  snapshot:
    name: "fluence-js"
    uses: ./.github/workflows/snapshot.yml

  aqua-snapshot:
    name: "aqua"
    needs:
      - snapshot

    uses: fluencelabs/aqua/.github/workflows/snapshot.yml@main
    with:
      fluence-js-version: ${{ needs.snapshot.outputs.fluence-js-version }}

  aqua-playground:
    needs:
      - snapshot
      - aqua-snapshot

    uses: fluencelabs/aqua-playground/.github/workflows/tests.yml@master
    with:
      fluence-js-version: ${{ needs.snapshot.outputs.fluence-js-version }}
      aqua-version: ${{ needs.aqua-snapshot.outputs.aqua-version }}
