name: "test"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/tests.yml"
      - "!.github/workflows/snapshot.yml"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/tests.yml"
      - "!.github/workflows/snapshot.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  tests:
    name: "js-client"
    uses: ./.github/workflows/tests.yml
    with:
      ref: ${{ github.ref }}
      nox-image: "docker.fluence.dev/nox:renovate-avm_4905_1"
