name: Run tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    env:
      RUST_PEER_IMAGE: fluencelabs/fluence

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Setup docker-compose
        uses: KengoTODA/actions-setup-docker-compose@v1.0.9
        with:
          version: 'v2.10.0'

      - name: Pull image
        run: docker pull ${RUST_PEER_IMAGE}

      - name: Run rust-peer
        uses: isbang/compose-action@v1.1.0
        with:
          compose-file: ".github/e2e/docker-compose.yml"
          down-flags: "--volumes"

      - name: Install deps
        run: pnpm i

      - name: Run tests
        run: |
          pnpm -r build
          pnpm -r test
        env:
          CI: true
